language: python
python:
    - 2.7
    - 3.5
    - 3.6
    - 3.7
    - 3.8
install:
    - pip install coverage coveralls
    - pip install -e .
script:
    - coverage run --source=ghdiff setup.py test -q
after_success:
    - coveralls
notifications:
    email: false
